# Generated by Django 5.0.6 on 2026-01-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Not Published', 'Not Published'), ('None', 'None')], default='Not Published', max_length=20),
        ),
    ]
